# Generated by Django 4.2.16 on 2024-11-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTreeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start',
            field=models.DateField(),
        ),
    ]
